### ISSUE TITLE
Would `NewCallbackCDecl` solve this?

### ISSUE THREAD

**Issue by hajimehoshi** [gonutz/sdl2-dll-issue#1]
https://golang.org/pkg/syscall/?GOOS=windows#NewCallbackCDecl

This is just my guess, but DLL's exported functions are cdecl by default. I run into similar problems (the stack was broken with 32bit DLL) and `NewCallbackCDecl` solved the issue.

**Comment by gonutz** [comment]
Yes! You are right! Thank you very much, that was the right call, pun  intended!

I looked it up in the sources and it says in [begin_code.h](https://hg.libsdl.org/SDL/file/c005c49beaa9/include/begin_code.h):

```
/* By default SDL uses the C calling convention */
#ifndef SDLCALL
#if (defined(__WIN32__) || defined(__WINRT__)) && !defined(__GNUC__)
#define SDLCALL __cdecl
```

This means that using the `stdcall` callback only worked by accident! Great catch, you really helped me out greatly here and I really appreciate it!
